Repository bismuthmoe/bismuth, pull requests merged in 2023-03, with the labels that each got.

#6 Add kick command
  commands/moderation/KickCommand.ts
Labels: type:commands, area:moderation

#7 Create an initial database schema
  .gitignore
  aurora.config.json
  bot.ts
  commands/information/PingCommand.ts
  commands/moderation/KickCommand.ts
  listeners/GuildCreateListener.ts
  package-lock.json
  package.json
  prisma/main.prisma
  prisma/migrations/20230326141318_initial_database/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/models/Guild.prisma
  prisma/models/User.prisma
  src/Iridium.ts
  src/providers/Provider.ts
  src/util/Constants.ts
Labels: size/M

#8 Create labels.yml
  .github/labels.yml
Labels: size/S

#10 Lowercase the size label names
  .github/labels.yml
Labels: size:s

#9 Fix chat command handling
  bot.ts
  commands/information/PingCommand.ts
  listeners/MessageCreate.ts
  listeners/commands/CommandRunListener.ts
  listeners/commands/errors/ChatCommandErrorListener.ts
  listeners/commands/errors/MessageCommandErrorListener.ts
  src/util/Events.ts
Labels: type:events, type:commands, size:l

#14 Expand commands for modularity
  commands/information/PingCommand.ts
  commands/moderation/KickCommand.ts
  src/Iridium.ts
  src/stores/IridiumCommandStore.ts
  src/stores/ProviderStore.ts
  src/structures/IridiumCommand.ts
Labels: type:framework, area:commands, size:m

#15 Create a README
  .github/FUNDING.yml
  LICENSE
  README.md
Labels: type:meta, area:yard-care, size:xl
